"""initial schema with StreamingDiskANN indexes

Revision ID: 0001
Revises:
Create Date: 2026-05-08 12:00:00.000000

A memory can be assembled from several frames, and in a multi-camera room from
several cameras, so a single ``sensor_id`` cannot name its origin. The column is
deliberately absent from both ``scene_observations`` and ``person_movements``;
per-frame provenance belongs in ``media_paths_json`` / ``objects_json``, which
hold one entry per contributing frame. ``idx_scene_obs_sensor_time`` went with
it; ``idx_scene_obs_room_time`` already covers the room-plus-time access pattern
that every query in ``app/services/search.py`` actually uses.
"""
from typing import Sequence, Union
from alembic import op


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- scene_observations ---
    op.execute("""
        CREATE TABLE scene_observations (
            id              BIGSERIAL PRIMARY KEY,
            room_id         TEXT,
            room_name       TEXT,
            observed_at     TIMESTAMPTZ NOT NULL,
            source          TEXT NOT NULL,

            objects_json    JSONB,
            persons_count   INT,
            hazard_flags    TEXT[],
            description     TEXT,
            object_list     TEXT[],

            workflow_execution_id  BIGINT,
            media_paths_json       JSONB,

            embedding               vector(768),
            description_embedding   vector(768),

            -- DL-M05: person_id attributes an observation to a resident;
            -- kind distinguishes record taxonomy ("scene" / "guided_episode" /
            -- "hygiene_verdict"). Both NULL on legacy scene rows, no backfill.
            person_id       TEXT,
            kind            TEXT,

            created_at      TIMESTAMPTZ DEFAULT NOW()
        );
    """)

    op.execute("""
        CREATE INDEX idx_scene_obs_person_id
            ON scene_observations (person_id);
    """)
    op.execute("""
        CREATE INDEX idx_scene_obs_kind
            ON scene_observations (kind);
    """)
    op.execute("""
        CREATE INDEX idx_scene_obs_room_time
            ON scene_observations (room_id, observed_at DESC);
    """)
    op.execute("""
        CREATE INDEX idx_scene_obs_hazards
            ON scene_observations USING GIN (hazard_flags);
    """)
    op.execute("""
        CREATE INDEX idx_scene_obs_objects
            ON scene_observations USING GIN (object_list);
    """)

    # StreamingDiskANN indexes (pgvectorscale) — disk-backed, more performant than HNSW
    op.execute("""
        CREATE INDEX idx_scene_obs_embedding
            ON scene_observations USING diskann (embedding);
    """)
    op.execute("""
        CREATE INDEX idx_scene_obs_description_embedding
            ON scene_observations USING diskann (description_embedding);
    """)

    # --- person_movements ---
    op.execute("""
        CREATE TABLE person_movements (
            id              BIGSERIAL PRIMARY KEY,
            person_id       TEXT NOT NULL,
            person_name     TEXT,

            from_room_id    TEXT,
            to_room_id      TEXT,
            from_room_name  TEXT,
            to_room_name    TEXT,

            direction_raw   TEXT,
            direction_semantic TEXT,

            confidence      FLOAT,
            observed_at     TIMESTAMPTZ NOT NULL,
            observation_id  BIGINT REFERENCES scene_observations(id),

            created_at      TIMESTAMPTZ DEFAULT NOW()
        );
    """)
    op.execute("""
        CREATE INDEX idx_person_movements_person_time
            ON person_movements (person_id, observed_at DESC);
    """)
    op.execute("""
        CREATE INDEX idx_person_movements_room_time
            ON person_movements (to_room_id, observed_at DESC);
    """)

    op.execute("""
        CREATE MATERIALIZED VIEW person_current_location AS
        SELECT DISTINCT ON (person_id)
            person_id, person_name, to_room_id AS room_id, to_room_name AS room_name,
            direction_semantic, confidence, observed_at
        FROM person_movements
        WHERE to_room_id IS NOT NULL
        ORDER BY person_id, observed_at DESC;
    """)
    op.execute("""
        CREATE UNIQUE INDEX ON person_current_location (person_id);
    """)

    # --- object_presence ---
    op.execute("""
        CREATE TABLE object_presence (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            room_id         TEXT NOT NULL,
            object_label    TEXT NOT NULL,
            first_seen_at   TIMESTAMPTZ NOT NULL,
            last_seen_at    TIMESTAMPTZ NOT NULL,
            observation_count INT DEFAULT 1,
            last_observation_id BIGINT REFERENCES scene_observations(id)
        );
    """)
    op.execute("""
        CREATE UNIQUE INDEX ON object_presence (room_id, object_label);
    """)


def downgrade() -> None:
    op.execute("DROP MATERIALIZED VIEW IF EXISTS person_current_location CASCADE;")
    op.execute("DROP TABLE IF EXISTS object_presence CASCADE;")
    op.execute("DROP TABLE IF EXISTS person_movements CASCADE;")
    op.execute("DROP TABLE IF EXISTS scene_observations CASCADE;")
