"""fix object_presence id to identity

Revision ID: a3f9c956640a
Revises: 957e5f52208f
Create Date: 2026-05-07 11:32:24.159162
"""
from typing import Sequence, Union
from alembic import op


revision: str = 'a3f9c956640a'
down_revision: Union[str, None] = '957e5f52208f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        ALTER TABLE object_presence
        ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    """)
    op.execute("""
        SELECT setval(
            pg_get_serial_sequence('object_presence', 'id'),
            COALESCE(MAX(id), 1)
        ) FROM object_presence;
    """)


def downgrade() -> None:
    op.execute("""
        ALTER TABLE object_presence
        ALTER COLUMN id DROP IDENTITY IF EXISTS;
    """)
